baseurl: /
url: https://alxira5.vercel.app
domain: alxira5.vercel.app

title: Alxira5

lang: en

locale: en_US

author:
  name: Guillermo Brito
  picture: /assets/images/alxira5.jpg
  twitter: Alxira5
  url: https://alxira5.vercel.app/
  email: alxira5@gmail.com

description: >-
  Software developer and digital artist, defender of free culture.

tagline: The Alxira5 personal website in the network.

logo: /assets/images/avatar.svg

twitter:
  username: Alxira5
  cad: summary_large_image

social:
  name: Guillermo Brito
  links:
    - https://github.com/Alxira5
    - https://www.youtube.com/@Alxira5
    - https://soundcloud.com/alxira5
    - https://mastodon.social/@Alxira5
    - https://x.com/Alxira5

webmaster_verifications:
  google: dGGfSr0CqYOO8aqpUMRluHF8tzj9wNxBURV_prRd3Vs
  bing: 29C8E8925A64BE85BDB69C975B67DDD0

feed:
  path: /blog/feed.xml

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /assets/images/social-card.png
        alt: Social card

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - blog.md
  - about.html
  - avatar.html
  - contact.html

minima:
  social_links:
    - { platform: github,     title: GitHub,     user_url: "https://github.com/Alxira5" }
    - { platform: youtube,    title: YouTube,    user_url: "https://www.youtube.com/@Alxira5" }
    - { platform: soundcloud, title: SoundCloud, user_url: "https://soundcloud.com/alxira5" }
    - { platform: mastodon,   title: Mastodon,   user_url: "https://mastodon.social/@Alxira5" }
    - { platform: x,          title: X,          user_url: "https://x.com/Alxira5" }

exclude:
  - README.md
  - LICENSE
  - ASSET_LICENSE
  - .sass-cache/
  - .jekyll-cache/
  - .vercel/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
